"""add users table

Revision ID: 079ad1d9f5bd
Revises: 512d0c1c764e
Create Date: 2026-05-10 18:16:16.572217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079ad1d9f5bd'
down_revision: Union[str, Sequence[str], None] = '512d0c1c764e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('employees', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'employees', ['user_id'])
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('owners', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'owners', ['user_id'])
    op.create_foreign_key(None, 'owners', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owners', type_='foreignkey')
    op.drop_constraint(None, 'owners', type_='unique')
    op.drop_column('owners', 'user_id')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
